name: Docker Image of the Server
on:
  push:
    branches: [ "master", "feature/ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Copying the protocol files
      run: cp -rv shared/protocol server/protocol
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build the Docker image
      working-directory: server
      run: docker build . --file Dockerfile --tag cyberverse-server:$(date +%s)
